name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: compile
        run: echo "Hello World!"
      - name: unit testing
        run: echo "Hello idream!"
      - name: package
        run: echo "Hello nishankainfotech!"
